### ISSUE TITLE
How to set match level

### ISSUE THREAD

**Issue by Hibiskua** [applitools/eyes.cypress#1]
Hi,
it is any way how to set another **match level**? I try find any method but unsuccessfully. Can you help me, please?

**Comment by amitzur** [comment]
This will be available in the upcoming version. We'll update here as well when it's ready

**Comment by Hibiskua** [comment]
Nice,
Thank you.

**Comment by amitzur** [comment]
Support for **match level** is now available in version 1.5.14
It's possible to pass matchLevel in the call to `cy.eyesOpen` as described in this section:
https://github.com/applitools/eyes.cypress#advanced-configuration
