### ISSUE TITLE
Error: failed to render screenshot

### ISSUE THREAD

**Issue by igor-starostenko-ag** [applitools/eyes.cypress#10]
Started seeing these errors randomly in different tests:
```
Errors - 1 tests.

			1) Error: failed to render screenshot



Because this error occurred during a 'after all' hook we are skipping all of the remaining tests.

      at Context.send.then.resp (https://***.com/__cypress/tests?p=cypress/support/index.js-020:161:13)

```

@applitools/eyes.cypress@3.2.1
cypress@3.1.0

**Comment by amitzur** [comment]
Hi @igor-starostenko-ag, so sorry we took so long to respond! We normally reply within the day.
Does this still happen to you?
If so, could you run the test with logs enabled and send them to us to `amit.zur@applitools.com` ?

You can enable logs by either defining the environment variable `APPLITOOLS_SHOW_LOGS=true` or by specifying in the `applitools.config.js` file the property `showLogs: true`.

Thanks!

**Comment by amitzur** [comment]
Hi @igor-starostenko-ag , would you like us to take a look at the logs?

**Comment by igor-starostenko-ag** [comment]
Hi @amitzur . I haven't ran into this issue since last week. It isn't consistently reproducible. I'll post the logs here if I manage to catch it. Thanks!

**Comment by amitzur** [comment]
Could you send me the entire log file to amit.zur@applitools.com ?
Thanks!

**Comment by amitzur** [comment]
Hi @igor-starostenko-ag since we are handling this in our support system, can I close this issue?

**Comment by amitzur** [comment]
thanks!

**Comment by rocketsurgeonboic** [comment]
This happened to us because of the duplication of testName or tag properties between tests. Copy paste errors.
If the log message would indicate such a thing, that would help diagnosis.
