### ISSUE TITLE
Import Commands Error

### ISSUE THREAD

**Issue by erdavids** [applitools/eyes.cypress#13]
I tried setting up with `npx eyes-setup` and received this error...

<img width="563" alt="screen shot 2018-11-12 at 10 07 09 am" src="https://user-images.githubusercontent.com/16595946/48356452-4e534c00-e664-11e8-812d-e99e10c30bea.png">

After that I added the necessary statements manually, but when I add `import '@applitools/eyes.cypress/commands'` to my index.js file, I receive this error in Cypress...

<img width="630" alt="screen shot 2018-11-12 at 10 09 55 am" src="https://user-images.githubusercontent.com/16595946/48356518-76db4600-e664-11e8-8bee-ea13ba9d99d2.png">

I am seeing the "batchEnd" mentioned in the error in the imported commands.js file, so I believe that the import is working and somewhere in the process the cy.request is reaching out to localhost.

Let me know if I can provide any additional information

**Comment by amitzur** [comment]
First, it's strange that the `npx eyes-setup` command didn't recognize the script. You might try to reinstall `@applitools/eyes.cypress` if you feel like it.
Regarding the issue - did you also manually add the line in the `pluginsFile` as described [here](https://www.npmjs.com/package/@applitools/eyes.cypress#configure-eyescypress-plugin)?

**Comment by erdavids** [comment]
Thank you for the fast response! I did add the line to the pluginsFile, but it looks like I had it inside the definition of module.exports. 

I reinstalled `@applitools/eyes.cypress`, verified the line additions, and restarted Cypress and now it is working! I was not able to get `npx eyes-setup` to work however. 

Thank you for your help!

**Comment by amitzur** [comment]
Glad I could help!
As for the `npx` command - maybe it's an npm/node version issue? what versions are you using?
