### ISSUE TITLE
test not using applitools breaks with "APPLITOOLS_API_KEY env variable is missing"

### ISSUE THREAD

**Issue by Bobgy** [applitools/eyes.cypress#14]
I have applitools integration (plugin and commands), but I don't always run it for cypress tests.
After some recent version update a test not calling any applitools commands also breaks with the error "APPLITOOLS_API_KEY env variable is missing" in beforeAll hook, even if it's just an empty test.

current:
if running an empty test without APPLITOOLS_API_KEY, it fails
expected:
it should pass

**Comment by amitzur** [comment]
Hi @Bobgy and thanks for taking the time to check the version the bug was introduced. It is fixed now, in version 3.3.14

Indeed, a breaking change to the API was erroneously introduced out of a major version. This was an enforcement of the following note in the readme:

>The following configuration properties cannot be defined using the first method of passing them to `cy.eyesOpen`. They should be defined either in the `applitools.config.js` file or as environment variables.

**Comment by tienbuiniteco** [comment]
Hi @amitzur do you have any further investigation on this matter? 
This issue suddenly happened in my test project, even though all of the properties are defined in applitools.config.js. It used to work properly before.
I'm currently using latest cypress and @applitools/eyes-cypress, I tried to reinstall older version but find no luck "@applitools/eyes-cypress": "^3.6.35",
    "cypress": "^3.2.0"
![image](https://user-images.githubusercontent.com/14124923/61536636-5c4c3e80-aa35-11e9-9e48-a23735a90504.png)

**Comment by danielschwartz85** [comment]
Hi @tienbuiniteco ,

**Comment by automationJatinder** [comment]
I am also facing this problem. I have added APPLITOLS_API_KEY in ENV variable and on echo %APPLITOLS_API_KEY% I can see my key. I have also added the key in applitools.config.js. but no luck

Can anyone help please @tienbuiniteco @danielschwartz85

**Comment by danielschwartz85** [comment]
@automationJatinder - there's a misspell in your env variable name (and in my exaple, sorry); use APPLITOOLS_API_KEY (two "O"s).
