### ISSUE TITLE
Installation fails: E404

### ISSUE THREAD

**Issue by justmoon** [applitools/eyes.cypress#4]
With the latest version the installation fails with an E404 error:

```
$ npm i @applitools/eyes.cypress
npm ERR! code E404
npm ERR! 404 Not Found: @applitools/monitoring-commons@^1.0.6
```

Dependency chain:

`@applitools/eyes.cypress -> @applitools/visual-grid-client -> @applitools/http-commons -> @applitools/monitoring-commons`

See dependencies for @applitools/http-commons:

https://www.npmjs.com/package/@applitools/http-commons

And @applitools/monitoring-commons doesn't exist / is private:

https://www.npmjs.com/package/@applitools/monitoring-commons

**Comment by amitzur** [comment]
fixed now, thanks!
