### ISSUE TITLE
applitools.config.js configuration is not being read

### ISSUE THREAD

**Issue by alon1980** [applitools/eyes.cypress#7]
When adding that file next to cypress.json (same folder) and configuring it with 
`module.exports = {
    matchLevel: 'Layout'
};`

The matchLevel stays strict.

**Comment by alon1980** [comment]
Hi, thanks for responding. 
Version 3.2.1

**Comment by amitzur** [comment]
That's strange. Can you run cypress with env variable `APPLITOOLS_SHOW_LOGS=true` and paste it here? If it's long just copy the first 100 lines or so

**Comment by amitzur** [comment]
Hey there. Were you able to resolve this and run successfully with the config file?

**Comment by amitzur** [comment]
Closing this as we've learned you managed to get this to work
